export { default as removeObjectItemFromList } from './removeObjectItemFromList'
export { default as updateObjectItemInList } from './updateObjectItemInList'
export { default as sortArrayOfObjects } from './sortArrayOfObjects'
export { default as validateSimpleInput } from './validateSimpleInput'
export { default as pointContextCapitalized } from './pointContextCapitalized'
